### ISSUE TITLE
Deleting a folder from Admin

### ISSUE THREAD

**Issue by websemantics** [anomalylabs/files-module#15]
![delete-folder](https://cloud.githubusercontent.com/assets/2190455/11480177/05b8a456-9764-11e5-943a-9121a1ab7f01.png)

This also causes a conflict next time I try to create a folder with the same slug

  ```[Illuminate\Database\QueryException]
  SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'files-css'
  for key 'streams_streams_namespace_slug_unique' (SQL: insert into `default_streams
  _streams` (`namespace`, `slug`, `translatable`, `locked`, `config`, `prefix`) valu
  es (files, css, 1, 0, a:0:{}, files_))```

**Comment by websemantics** [comment]
I can see the stream for the folder still in the 'default_streams_streams' .. removing that manually solves the Integrity constraint violation

**Comment by RyanThompson** [comment]
If this is still a thing please open in main repo!
