### ISSUE TITLE
DiskModel filesystem  :/

### ISSUE THREAD

**Issue by websemantics** [anomalylabs/files-module#16]
Calling method filesystem() on DiskModel generates BadMethodCallException

https://github.com/anomalylabs/files-module/blob/master/src/Disk/DiskModel.php#L34

![disk](https://cloud.githubusercontent.com/assets/2190455/11490098/57e47464-97a3-11e5-9eaa-3776a0a72d4a.png)

**Comment by websemantics** [comment]
Using code from https://github.com/anomalylabs/files-module/blob/master/src/File/FileUploader.php#L95
as an alternative for now ..

**Comment by RyanThompson** [comment]
If this is still a thing please open in main repo!
