### ISSUE TITLE
Can't create Folder

### ISSUE THREAD

**Issue by budhead** [anomalylabs/files-module#18]
It seems like it expects field type in FolderFormBuilder, but after I added field types for slug, description and allowed_types, there is a problem in save.
When I removed this fields everything works like a charm ... and as I saw in the database ... this fields are not there. Maybe they should be removed?

![screen shot 2015-12-16 at 9 39 26](https://cloud.githubusercontent.com/assets/2962473/11834891/07c78a06-a3d9-11e5-9952-4b42b66243c9.png)

**Comment by RyanThompson** [comment]
This is on a fresh install? What do you mean you removed the fields? They're core fields.


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by budhead** [comment]
I removed them from the array in the file :)
It is not really a fresh install, because I'm using it from about a month, but It's my first time to deal with this module.
I'll try fresh install. Maybe something went wrong with the updates.

**Comment by RyanThompson** [comment]
Ah ya - def reinstall. Schema changes with the B2 release. 


Ryan Thompson
President / CEO / Streams Evangelist
PyroCMS, Inc.
www.pyrocms.com

t (877) 705-0806
m (309) 752-8581

**Comment by budhead** [comment]
Yup, fresh install fixed everything ... but maybe you should think of more reliable migrations or update guide?

**Comment by RyanThompson** [comment]
It was only Beta1 to Beta2 - no need. B2 is stable and will utilize migrations going forward: https://www.pyrocms.com/articles/pyrocms-3-beta2
