### ISSUE TITLE
New Folder button doesn't work if you are inside a folder that has a space in it.

### ISSUE THREAD

**Issue by bloveless** [anomalylabs/files-module#2]
Add "Main Content Images" as the first folder and it writes the button as "/admin/files/folders/create/local/Main Content Images". So when it submits it only uses "/admin/files/folders/create/local/Main". Which doesn't exist.

**Comment by bloveless** [comment]
To reproduce I added a root level folder called "Main Content Images" then clicked into that folder. Tried to add another folder as the child of "Main Content Images" named "Home Page" clicking "New Folder" causes an empty modal to show up.

**Comment by RyanThompson** [comment]
Fixed: https://github.com/anomalylabs/streams-platform/commit/b2272d505359a825d94ea9a5fac928043d482f3b

Also pull anomaly theme! JS update in there.

**Comment by bloveless** [comment]
Thanks!
