### ISSUE TITLE
Redirect is not being parsed after navigation link create

### ISSUE THREAD

**Issue by bloveless** [anomalylabs/files-module#3]
Create new navigation link (URL)

Name: Test
URL: test

![screen shot 2015-07-01 at 1 16 15 pm](https://cloud.githubusercontent.com/assets/535135/8462784/700ddb5c-1ff3-11e5-97c1-ad197a566ea0.png)

%7Broute.parameters.group%7D is in the url

**Comment by bloveless** [comment]
I'm poking around a bit with this, but am having a hard time figuring out where the form save action is being parsed. Or not being parsed.

**Comment by RyanThompson** [comment]
Oh I need to check that out - Itll be in the form builder

**Comment by RyanThompson** [comment]
Pry isnt being parsed (in the input class for the form actions)

**Comment by bloveless** [comment]
I’m looking into it. Looks like there is an issue in the tree buttons as well.

Brennon Loveless 
brennon.loveless@gmail.com

**Comment by RyanThompson** [comment]
Ya I only put it in the pertinent classes but you can basically copy the FooParser class from say.. form actions and put it in the others.. The parser get's injected into the FooInput class.


Ryan Thompson
President / CEO
AnomalyLabs, Inc.
www.anomaly.is<http://www.anomaly.is>

t (877) 705-0806
m (309) 752-8581



On Jul 1, 2015, at 2:28 PM, bloveless <notifications@github.com<mailto:notifications@github.com>> wrote:

I’m looking into it. Looks like there is an issue in the tree buttons as well.

Brennon Loveless 
brennon.loveless@gmail.com<mailto:brennon.loveless@gmail.com>
