### ISSUE TITLE
Cannot create local storage adapter

### ISSUE THREAD

**Issue by bloveless** [anomalylabs/files-module#4]
![screen shot 2015-07-01 at 11 42 18 pm](https://cloud.githubusercontent.com/assets/535135/8470578/ec7f6604-204a-11e5-8d8b-05e0b1ce1c40.png)

**Comment by bloveless** [comment]
This is after trying to save a new Local disk named "Local"

**Comment by RyanThompson** [comment]
Pull streams-platform and retry.. my bad

**Comment by bloveless** [comment]
Fixed!
