### ISSUE TITLE
Upload error messages are unreadable

### ISSUE THREAD

**Issue by bloveless** [anomalylabs/files-module#5]
![screen shot 2015-07-01 at 11 49 43 pm](https://cloud.githubusercontent.com/assets/535135/8470649/0b8b0e30-204c-11e5-8b0e-a5c8ee13355b.png)

**Comment by RyanThompson** [comment]
I personally hate the way the upload works right now so.. I think I am going to rethink this.

**Comment by RyanThompson** [comment]
I think Ill bind the file selector to the upload button - and make the whole screen droppable.
